### ISSUE TITLE
手机端好像不支持

### ISSUE THREAD

**Issue by Danielypzhang** [zxhd863943427/siyuan-plugin-flash-enhance#1]
手机端没有出现按钮,用浏览器打开也没有.

**Comment by zxhd863943427** [comment]
支持手机端的，只不过目前是需要浏览器伺服后在插件管理界面打开。手机界面单击是一键制卡，需要长按打开设置界面。

另外，一键制卡在移动端不可用，其他貌似可以。

没有太多精力和能力兼顾移动端适配，抱歉。
