### ISSUE TITLE
希望给一键制卡添加一个快捷键（非必要），制卡完成的提示也改一下（有一定的需求）

### ISSUE THREAD

**Issue by Aiviokoo** [zxhd863943427/siyuan-plugin-flash-enhance#10]
![image](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/87182333/63151037-ce2a-4971-9f84-e3c5f4309f2c)
现在提示的只有总的卡数，其实每一次制卡，我都不知道新增了多少张卡的，还是有一点点小焦虑。
希望可以显示

新增多少张卡
原有多少张卡→现有多少张卡

**Comment by zxhd863943427** [comment]
额，没办法获取原有的卡片数量的，且目前的实现没办法准确得到新增加的卡片，因为所有标记的卡片都会被重新添加一次。

我先增加快捷键支持，下个版本支持新增卡片显示

**Comment by zxhd863943427** [comment]
改了实现后能只制卡未制卡的部分，但是就会失去强制刷新的功能了。

不过目前动态制卡还算稳定，这应该不是问题。
