### ISSUE TITLE
自定义摘录效果

### ISSUE THREAD

**Issue by LAD021** [zxhd863943427/siyuan-plugin-flash-enhance#13]
Alt+Q摘录时默认的背景色效果可能与部分主题颜色冲突
请问能否增加自定义摘录背景色效果的功能？只要类似球衣主客场切换，有两种色调就行。

https://github.com/Achuan-2/siyuan-themes-tsundoku/issues/85

**Comment by zxhd863943427** [comment]
你好，这个颜色并不是自定义的颜色，而是使用了字体颜色中的第一种背景色。

**Comment by zxhd863943427** [comment]
如需修改，可以自行修改字体配色的第一种背景色，或使用配色方案插件。
