### ISSUE TITLE
【bug】当文档很大时一键删除无法删除干净问题

### ISSUE THREAD

**Issue by hackerhui** [zxhd863943427/siyuan-plugin-flash-enhance#15]
第一步，建一个长文档
第二步，在全文各处理制卡
第三步：回到文档顶部
第四步：右键删除文档卡片
结果，未删除干净
推测延迟加载部分文本内有制卡的未删除

**Comment by zxhd863943427** [comment]
目前使用的是前端读取页面的方式获取卡片，该限制无法避免，不属于bug。

调大动态加载块也可以缓解，切换到后端sql查询的方法可以克服当前限制。不过作者最近没啥时间，如能pr，非常感谢。
