### ISSUE TITLE
如何快速将摘录卡移出闪卡行列？

### ISSUE THREAD

**Issue by Samuelxiaozhuofeng** [zxhd863943427/siyuan-plugin-flash-enhance#17]
作者大大您好，非常感谢您的增强插件，现在有一个疑问，就是在渐进阅读过程中，如何快速把卡片移出复习行列？
我举个流程：
1. 阅读：阅读过程中通过alt+q对感兴趣的内容进行摘录，制作为卡片，例如现在有一张卡片A；
2. 刷卡：刷卡过程中刷到卡片A，对A的内容又进一步提取，随后alt+q提取出卡片B；
3. 管理：从卡片A中摘录出卡片B后，我发觉A已经失去价值了，希望移出复习行列，但我发现，闪卡列表中没有移除，或暂停卡片的选项；
我需要做以下操作：
**退出**闪卡界面，在众多摘录卡片中找到**卡片**A，然后点击，进入卡片A后，点击二级标题，快捷键ctrl+alt+f快捷取消制卡；
这个过程十分消耗时间，断开心流，而且卡片如果达到几十张上百张，你去找它就跟米粒里找沙子一样困难；

---
所以想问问接下来会出一个快捷取消卡片的功能吗？或者说 现在是有的，我应该如何实现？

谢谢您！

**Comment by zxhd863943427** [comment]
现在其实也可以从闪卡界面直接取消制卡，但是也不容易。

如果是文档的话，可以点击面包屑旁边的文档块标取消制卡，如果是其他类型的，可以直接在闪卡界面中取消。

这确实很麻烦，在思源官方的复习界面上也是第三方难以解决的，因为官方没有留下当前是哪张闪卡的信息，而思源又是允许嵌套闪卡的……

我之后考虑的方向是自起炉灶，使用官方的间隔复习接口重新写一个复习闪卡的界面，这样能一次性的解决很多问题，包括在移动端面包屑没了的问题。不过这个工作量略大，年内解决不了……

我现在是在做闪卡插件的图片遮挡功能，目前还有一个问题解决不了，界面缩放后图像会移位，暂时放弃解决，处理完另一个小问题后应该就会上架了。

下一步的规划是写一个问题的提取界面，大概就是能在 pdf、思源文档的摘录部分增加一个菜单，直接在浮窗上新建闪卡，而不需要进入文档。

再下一步才是重写界面……

反正，饼是画了，做就难了:|

**Comment by zxhd863943427** [comment]
已在增强界面中实现。
