### ISSUE TITLE
支持含有多个标记挖空的闪卡在间隔复习界面单个显示答案

### ISSUE THREAD

**Issue by EberhardLin** [zxhd863943427/siyuan-plugin-flash-enhance#20]
链滴帖子：https://ld246.com/article/1697164153040

支持标题块制卡后，我更习惯直接标题块制卡，但一旦闪卡含有多个标记挖空的话，只能通过显示答案来一键显示答案，感觉不太方便。

D大说官方就不支持了，可以考虑通过插件的方式实现。于是我就想到了您的这款「闪卡增强」插件，希望您能考虑下支持这个特性。

虽然主题「Savor写未」有类似特性，但其是在编辑器也将标记挖空的内容隐形了，而我想要单独在间隔重复界面才显示该效果的，除此之外的其他地方则是正常不变。

我并不太懂技术，也许我这提议可能在实现上有难度，若是如此则无视我这提议并直接关闭issues吧。

感谢你的插件，很好用！

**Comment by zxhd863943427** [comment]
帖子下面的css片段就内实现你的要求了……没有什么必要进入插件。

**Comment by EberhardLin** [comment]
> 帖子下面的css片段就能实现你的要求了……没有什么必要进入插件。

好的，感谢。帖子下面的两个回复是在我提issue后才发的，当时没有这个，再次感谢，谢谢。
