### ISSUE TITLE
建议：文档代替卡包？能否将卡片集中放到某个文档中？而不是使用卡包。

### ISSUE THREAD

**Issue by leommjj** [zxhd863943427/siyuan-plugin-flash-enhance#24]
场景解释：例如我对A文档进行制卡，能否把卡片集中放到它的子文档中，等于是替代了卡包的功能。
好处：
一是可以管理和删除卡片，目前卡包好像不能集中管理卡片；
二是“文档做卡包”，可以进行移动组合，例如我期末考试，集中复习时，就把要复习的“文档卡包”放到一起，进行刷卡。

**Comment by leommjj** [comment]
在讲的详细一点，比如，我按`快捷键`制卡，自动把索引和文本集中放到一个子文档中。

**Comment by zxhd863943427** [comment]
你好，目前开发重点不在这里，但欢迎pr。
