### ISSUE TITLE
对闪卡中的.protyle-breadcrumb添加position:relative

### ISSUE THREAD

**Issue by chenshinshi** [zxhd863943427/siyuan-plugin-flash-enhance#25]
层级面包屑不适配一些面包屑样式是position:absolute的主题，例如zhang-light，我觉得在插件这边加代码会更方便些。
<img width="764" alt="2de50ce942d05ea3d0476e54b73402fa" src="https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/125173405/955b53a4-c9c5-4219-82ab-a36acdb791b0">

另外z佬有打算做单击显示挖空吗？突然发现现在通用的悬浮显示挖空不适配[...]。

**Comment by zxhd863943427** [comment]
插件层级面包屑这边要怎么动手呢？

挖空增强可以搞一个点击显示，不过我个人是觉得摘录后挖空更有前途一点: )

**Comment by zxhd863943427** [comment]
增加了一个点击显示

**Comment by zxhd863943427** [comment]
完成
