### ISSUE TITLE
关于“增加有序阅读资料”的疑问

### ISSUE THREAD

**Issue by mcthesw** [zxhd863943427/siyuan-plugin-flash-enhance#27]
闪卡增强有一个“增加有序阅读资料”的功能，但是使用后在闪卡菜单进行间隔重复，仍然没有顺序，请问这是需要进行其它的配置吗？

我的具体操作步骤如下：
1. 使用导入工具导入书籍
2. 在“更多”菜单进行“优化排版”
3. 选择“添加有序阅读材料”点击“按2级标题拆分”
4. 主菜单-闪卡-间隔重复
5. 此时展示的闪卡不是按照阅读顺序的

插件版本 v0.1.0
思源版本 v2.10.15

还有一个问题就是按照2级标题拆分的闪卡，遇到以下情况会只显示2级标题内的文本
```markdown
# 一级标题
这些文本不会在闪卡中出现
## 二级标题1
这些会出现1
## 二级标题2
这些会出现2
```
因为功能是按照2级标题拆分闪卡，所以出现这种情况确实非常合理，但是我想要阅读到那部分内容，作者有可以推荐的方法吗？如果能和我讲讲，我将非常感谢

**Comment by zxhd863943427** [comment]
目前没有办法。闪卡的排序请使用增强界面。

**Comment by mcthesw** [comment]
请问增强界面指的是“右键该插件图标-增强闪卡界面”这个开关吗？我开启后感觉进入闪卡界面没有变化，是要怎么操作呢

**Comment by zxhd863943427** [comment]
这是个自定义快捷键后使用快捷键开启的自定义界面，你需要先到快捷界面设置打开的快捷键，因为目前为alpha版，所以没有写文档说明。

另外，我发现插件集市中新上线了一个渐进阅读功能的插件，这个插件你也可以先看一下。
