### ISSUE TITLE
图片过高时，图片挖空的界面显示不完整

### ISSUE THREAD

**Issue by luo-chuan** [zxhd863943427/siyuan-plugin-flash-enhance#28]
如图，我用到手机伺服，图片过高时，图片挖空界面显示不完整，特别是下面的“保存”和“取消”按钮直接显示不出来。
![图片](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/33930736/d76b3df1-ff0c-4f6f-9b67-0fbb16ac4fc8)

**Comment by zxhd863943427** [comment]
不建议手机图片制卡，因为webview版本不齐，部分依赖的css无法生效。
