### ISSUE TITLE
给生成的文档添加序号 以方便排序

### ISSUE THREAD

**Issue by QQQOrange** [zxhd863943427/siyuan-plugin-flash-enhance#29]
思源不能设置单个文件夹排序规则，总体的规则总是按着首字母等，这样的话，分出来的摘要卡还是挖空卡基本都是乱序。
希望给每一个生成的子文档一个序号，这样能够方便排序，看起来也更直观一点

**Comment by zxhd863943427** [comment]
使用笔记本级别的自定义排序
