### ISSUE TITLE
[...]能够变的显眼 以至于在文字中的卡片中能够快速明确位置

### ISSUE THREAD

**Issue by QQQOrange** [zxhd863943427/siyuan-plugin-flash-enhance#33]
红字黄底的样式之类的

**Comment by zxhd863943427** [comment]
事实上在自定义界面中是很显眼的。

![图片](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/74853597/dbadcf07-e1cc-4687-989c-ad8ad3cb8ff2)

原文的话建议自行加css代码片段，这部分已经有行级标记可以定位。

**Comment by QQQOrange** [comment]
> 事实上在自定义界面中是很显眼的。
> 
> ![图片](https://private-user-images.githubusercontent.com/74853597/293333254-8a58e0de-1970-427e-a8c9-aa2c181afb41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDM1MzksIm5iZiI6MTcwMzg0MzIzOSwicGF0aCI6Ii83NDg1MzU5Ny8yOTMzMzMyNTQtOGE1OGUwZGUtMTk3MC00MjdlLWE4YzktYWEyYzE4MWFmYjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA5NDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzU4MTZmZjBlYjZkMGM4YTRlZGM0NmVkZDQ0MjhmZmEzMDU4NmRjYmQwYjlkZjE1MTRjNzUxYmJhYWM2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AUe1nb_TU461p8WX4dxNolvbu3hPFGXQmyOPLr9i2bo)
> 
> 原文的话建议自行加css代码片段，这部分已经有行级标记可以定位。

你这个不太行，在代码片段里面加入我提供的这一段代码，就能在正常的间隔重复中实现黄底红字。自定义界面说实话 太丑了

**Comment by QQQOrange** [comment]
> 事实上在自定义界面中是很显眼的。
> 
> ![图片](https://private-user-images.githubusercontent.com/74853597/293333254-8a58e0de-1970-427e-a8c9-aa2c181afb41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDM1MzksIm5iZiI6MTcwMzg0MzIzOSwicGF0aCI6Ii83NDg1MzU5Ny8yOTMzMzMyNTQtOGE1OGUwZGUtMTk3MC00MjdlLWE4YzktYWEyYzE4MWFmYjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA5NDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzU4MTZmZjBlYjZkMGM4YTRlZGM0NmVkZDQ0MjhmZmEzMDU4NmRjYmQwYjlkZjE1MTRjNzUxYmJhYWM2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AUe1nb_TU461p8WX4dxNolvbu3hPFGXQmyOPLr9i2bo)
> 
> 原文的话建议自行加css代码片段，这部分已经有行级标记可以定位。

.card__block--hidemark span[data-type~=mark]::before{background-color:yellow;color:red!important}
.card__block--hidemark span[data-type~=mark]::before {
    content: " [...] ";
    color: var(--b3-theme-on-background);
    font-size: 16px;}
.card__block--hidemark span[data-type~=mark] {
    font-size: 0px;
}

**Comment by zxhd863943427** [comment]
自定义界面目前是以实现功能为主，还没有开始考虑界面美化，暂停、顺序展示、sm形式的增加挖空、删除闪卡都是在这个界面进行，如果有好的美化方案欢迎pr或提出。

至于普通标记形式的挖空，目前挖空增强已经提供了一定的样式增强了，增加配色还是让用户自己自定义比较好。

其实sm形式的挖空本来也不打算加样式的，因为已经有了 `custom-hollow="true"` 作为自定义外观的位点，不过是为了和sm的样式统一才加加进去的。

**Comment by QQQOrange** [comment]
> 自定义界面目前是以实现功能为主，还没有开始考虑界面美化，暂停、顺序展示、sm形式的增加挖空、删除闪卡都是在这个界面进行，如果有好的美化方案欢迎pr或提出。
> 
> 至于普通标记形式的挖空，目前挖空增强已经提供了一定的样式增强了，增加配色还是让用户自己自定义比较好。
> 
> 其实sm形式的挖空本来也不打算加样式的，因为已经有了 `custom-hollow="true"` 作为自定义外观的位点，不过是为了和sm的样式统一才加加进去的。

好吧 只能期待了
