### ISSUE TITLE
remnote复习页面 似乎失效了

### ISSUE THREAD

**Issue by QQQOrange** [zxhd863943427/siyuan-plugin-flash-enhance#34]

**Comment by zxhd863943427** [comment]
移动端dom改版后已经不可用，只有pc端可用。这不是css能解决的问题，我更倾向于在之后自定义界面中完成，免得继续适配dom改变。

**Comment by QQQOrange** [comment]
> 移动端dom改版后已经不可用，只有pc端可用。这不是css能解决的问题，我更倾向于在之后自定义界面中完成，免得继续适配dom改变。

好家伙 自定义界面太丑了
