### ISSUE TITLE
公式挖空应为未来挖空分组做预留

### ISSUE THREAD

**Issue by luo-chuan** [zxhd863943427/siyuan-plugin-flash-enhance#35]
建议改进语法，目前的`\mark{xxxxxx}`语法没有对挖空进行分组。
可以参考anki的语法，比如将`{{1::sin^2x}}+{{2::\cos^2x}}=1`制作成如下两张卡片：
$[...]+\cos^2x=1$ 及 $\sin^2x+[...]=1$

![图片](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/33930736/b921d8f9-bb37-4ef6-a330-e1c1cdef25f0)
https://forum.remnote.io/t/cloze-support-for-math-latex/2542

当然要等思源支持了挖空分组才行，现在只能说为未来做预留。可以把这个issue开着，不急。

**Comment by zxhd863943427** [comment]
我不知道它们是怎么实现的，anki使用的是mathjax，没有参考对象是实现不了的。
