### ISSUE TITLE
渐进式阅读，多次摘录会有索引错误

### ISSUE THREAD

**Issue by suka233** [zxhd863943427/siyuan-plugin-flash-enhance#37]
### **具体操作如下：**
1.对A文档的任意段落点击alt+q，生成子文档B；
2.对子文档B的任意段落点击alt+q，生成子文档C；
### **然后过没多久，就会出现如下错误：**
![image](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/43712875/35cde454-5335-45db-ba4d-60e419eeef1c)
查看思源日志发现是重复id造成的
![image](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/43712875/54956e0a-70a6-471d-8a82-01400704f47a)
### 以下是实际截图：
B文档截图：
![image](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/43712875/0572a6ac-96f2-4d26-8482-af6f873bd100)
C文档截图：
![image](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/43712875/f9e64c06-7700-422a-84d9-8ce1e25c5bb5)

### 以下是排查结果：
排查发现是这两行代码，生成的`sourceRoadMd`会携带id信息，导致重复ID。
https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/blob/562be3b3be0a809bf59fd4c269ee84b783801ec3/src/api/IR.ts#L186
https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/blob/562be3b3be0a809bf59fd4c269ee84b783801ec3/src/api/IR.ts#L228

目前我的本地解决办法是把这个方法`getSelectionContent`的第一个参数改为StdMd，这样生成的`sourceRoadMd`就没有id信息了:
https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/blob/562be3b3be0a809bf59fd4c269ee84b783801ec3/src/api/IR.ts#L75

但是由于我不知道BlockDOM2StdMd和BlockDOM2Md有啥其它的差异，所以不确定有没有其它影响。。

**Comment by zxhd863943427** [comment]
感谢排查。StdMd和Md日常可见的最大区别应该就是超级块了，其他应该都是兼容的。

**Comment by zxhd863943427** [comment]
发现是生成摘录的时候忘记新建id了
