### ISSUE TITLE
一级子结构编辑后，闪卡失活

### ISSUE THREAD

**Issue by abd-liac** [zxhd863943427/siyuan-plugin-flash-enhance#38]
一级子结构编辑后，闪卡失活
![B SC }(YE{LM1PEY}JS7RZ0](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/88515612/b292805b-fb71-4db9-b94f-482efc51f14a)

Q1：这应该不是预期行为？
Q2：如果是预期行为，应对我的需求的最佳实践是啥呢？

**Comment by zxhd863943427** [comment]
非预期行为，应该是bug，是最新版吗？

**Comment by zxhd863943427** [comment]
已修复
