### ISSUE TITLE
二级结构在间隔系统中缺失显示

### ISSUE THREAD

**Issue by abd-liac** [zxhd863943427/siyuan-plugin-flash-enhance#39]
![IBOD)N@CX9UUH63I7J)FYZS](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/88515612/1ded91cc-6f3b-4990-afee-473028216343)
Q1：这应该不是预期行为？
Q2：如果是预期行为，应对我的需求的最佳实践是啥呢？

**Comment by zxhd863943427** [comment]
一半的预期行为，这是分层闪卡的效果，但理论上是把a1制成闪卡才会影响a11的显示。

你可以把功能开关的这部分关闭，顺便问一下是最新版吗？

**Comment by zxhd863943427** [comment]
已修复
