### ISSUE TITLE
图片遮挡功能失效

### ISSUE THREAD

**Issue by Peter-8263** [zxhd863943427/siyuan-plugin-flash-enhance#43]
用的是“闪卡增强”插件，不知道是因为插件更新了还是思源更新了，间隔重复时会直接显示图片，不再显示遮挡块，但是制作图片遮挡卡遮挡块正常

**Comment by TCOTC** [comment]
关联 https://ld246.com/article/1731209225015

**Comment by zxhd863943427** [comment]
在我这里正常：

![Uploading 图片.png…]()

版本为v3.1.11正式版，请检查是否与其他插件冲突。

**Comment by zxhd863943427** [comment]
在我这里正常：

![图片](https://github.com/user-attachments/assets/1209d097-53db-4a7a-b695-e721b3c4c7a6)


测试版本为v3.1.11正式版，请检查是否与其他插件冲突。

**Comment by zxhd863943427** [comment]
嘶，好像是我之前本地测试修复完后，忘记发新版了。更新插件看看。

**Comment by Peter-8263** [comment]
![图片](https://github.com/user-attachments/assets/76a2b9fb-398f-42e8-a041-f84f0a272416)

插件市场未见更新（23：23）

**Comment by Peter-8263** [comment]
已解决
