### ISSUE TITLE
渐进式阅读的摘录是粉色的背景，当我删除这个摘录后，该如何去除粉色背景？

### ISSUE THREAD

**Issue by qiuqiao** [zxhd863943427/siyuan-plugin-flash-enhance#5]
版本：siyuan 2.8.9

插件是从集市里下载的

另外就是重新摘录已经摘录过的部分，有时候会出现运行时错误，出现两三次了，但我复现不了

**Comment by zxhd863943427** [comment]
这就是普通的背景颜色而已，去除字体样式即可。

**Comment by zxhd863943427** [comment]
另外，出现运行时错误假如能复现可以发一下，我在测试的时候没有见到。
