### ISSUE TITLE
[bug] 开启插件后，使用新窗口打开无内容显示

### ISSUE THREAD

**Issue by tcmtom** [zxhd863943427/siyuan-plugin-flash-enhance#8]
录屏如下：

https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/94541098/e6dd7414-e9c4-4ce9-ab4c-047ae7d7d375

插件设置如图：

![image](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/assets/94541098/1fa0a6b4-4176-45bc-965e-92d7770136e6)

**Comment by zxhd863943427** [comment]
我无法复现你的结果，这个貌似不是闪卡插件的问题。

**Comment by zxhd863943427** [comment]
请在新版本的思源中尝试能否复现
