### ISSUE TITLE
摘录后原文中的的超链接丢失

### ISSUE THREAD

**Issue by canzj** [zxhd863943427/siyuan-plugin-flash-enhance#9]
使用渐进阅读的摘录功能，对选中块执行摘录后，块背景被高亮，但同时块中的超链接文本被转换成了普通文本，导致超链接丢失。
期望是能够在更新原文时能够保留其中的超链接。

Siyuan 版本：2.9.1
系统：macOS

**Comment by canzj** [comment]
可能和思源API`/api/attr/setBlockAttrs`的行为有关。

相关源码：
https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/blob/fda1f3296dcf8caff2f4362fd9a443cce642ab39/src/api/IR.ts#LL191C14-L191C14

**Comment by zxhd863943427** [comment]
跟这个无关，是因为目前行级摘录的实现借鉴了dark+的评论，属于是直接在选中部分左右加入span标签，这导致会在持久化后被思源过滤掉其中的子标签，表现为丢失全部行级元素。

新版本的改进已经在本地的dev版本中实现了，目前能在跨块级元素摘录的情况下不丢失行级元素，但未能解决摘录时就处在块级元素中间时的问题。

思源中的源码应该是解决了这个问题，但我还没有时间查看实现，如果你有时间可以帮我找一下具体在哪里。

这是尚未发布的dev版的打包，你可以先手动替换一下看是不是解决了你的问题。


[package.zip](https://github.com/zxhd863943427/siyuan-plugin-flash-enhance/files/11765251/package.zip)

**Comment by zxhd863943427** [comment]
应该已经解决了
